version: "3.7"

services:
  production:
    container_name: __github-action-demo
    image: '__github-action-demo'
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    ports:
      - "5001:80"
