# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SPA mode in docker hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    # clone the repo
    - uses: actions/checkout@v2
    # setup docker-compose
    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '1.26.2'
    # push it to docker hub
    - run: |
        docker-compose up -d --build --remove-orphans -V && docker commit $(docker ps -a -q --filter ancestor=github-action-demo --format="{{.ID}}") mmarifat/github-action-demo
        docker login -u mmarifat -p 12345test && docker push mmarifat/github-action-demo
